//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDriver
    {
        public int Id { get; set; }
        public string DriverName { get; set; }
        public string DriverMobile { get; set; }
        public string NumberPlates { get; set; }
    }
}
