//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHavaleh
    {
        public int Id { get; set; }
        public Nullable<short> Factory_Id { get; set; }
        public Nullable<short> County_Id { get; set; }
        public Nullable<short> Buyer_Id { get; set; }
        public Nullable<int> Driver_Id { get; set; }
        public Nullable<short> VehicleType_Id { get; set; }
        public string Date { get; set; }
        public string Number { get; set; }
        public string HavlehNumber { get; set; }
        public string HavlehDate { get; set; }
        public string HavalehEndDate { get; set; }
    }
}
